import { ApiModuleData } from './api-module.model';

export const API_MODULES: ApiModuleData[] = [
  {
    key: 'authentication',
    name: 'Authentication',
    type: 'Platform',
    mountPoints: ['/authentication'],
    description: 'Handles the entire identity lifecycle: account registration, JWT login, session management, OAuth2 (Google), and user profile management.',
    status: 'stable',
    icon: 'pi pi-lock',
    features: [
      { name: 'Account Registration', description: 'Create a new account with email + password, send OTP verification via email' },
      { name: 'JWT Login', description: 'Authenticate with email/password, issue access + refresh token' },
      { name: 'Google OAuth2', description: 'Google OAuth2 flow, auto-create account if not exists' },
      { name: 'Token Refresh', description: 'Exchange refresh token for a new access token' },
      { name: 'Session Management', description: 'List, revoke single session, revoke all sessions' },
      { name: 'Password Reset', description: 'Forgot password flow with OTP via email' },
      { name: 'Email Verification', description: 'Verify email with OTP code' },
      { name: 'Profile Management', description: 'PATCH account + user profile (display name, avatar, ...)' },
      { name: 'Token Introspection', description: 'Validate/introspect any Bearer token' },
      { name: 'User Enrichment', description: '/me and /user/{id} returns roles, permissions, teams, Casbin rules' },
    ],
    endpoints: [
      { method: 'POST', path: '/authentication/register', auth: false, description: 'Register new account' },
      { method: 'POST', path: '/authentication/login', auth: false, description: 'Login, receive JWT' },
      { method: 'POST', path: '/authentication/refresh-token', auth: false, description: 'Exchange refresh token' },
      { method: 'POST', path: '/authentication/reset-password', auth: false, description: 'Send password reset OTP' },
      { method: 'POST', path: '/authentication/forgot-password', auth: false, description: 'Alias for reset-password' },
      { method: 'POST', path: '/authentication/update-password', auth: false, description: 'Set new password with OTP' },
      { method: 'POST', path: '/authentication/set-password', auth: false, description: 'Alias for update-password' },
      { method: 'POST', path: '/authentication/verify-email', auth: false, description: 'Verify email with OTP' },
      { method: 'POST', path: '/authentication/resend-verification', auth: false, description: 'Resend verification OTP' },
      { method: 'GET', path: '/authentication/google', auth: false, description: 'Initialize Google OAuth2 flow' },
      { method: 'GET', path: '/authentication/google/callback', auth: false, description: 'Google OAuth2 callback' },
      { method: 'POST', path: '/authentication/verify-token', auth: false, description: 'Introspect / validate token' },
      { method: 'GET', path: '/authentication/me', auth: true, description: 'Current account info' },
      { method: 'PATCH', path: '/authentication/me', auth: true, description: 'Update account profile' },
      { method: 'PATCH', path: '/authentication/me/profile', auth: true, description: 'Update user profile' },
      { method: 'DELETE', path: '/authentication/me', auth: true, description: 'Delete account' },
      { method: 'GET', path: '/authentication/me/sessions', auth: true, description: 'List active sessions' },
      { method: 'DELETE', path: '/authentication/me/sessions', auth: true, description: 'Revoke all sessions' },
      { method: 'POST', path: '/authentication/logout', auth: true, description: 'Logout (revoke current session)' },
      { method: 'POST', path: '/authentication/revoke-session', auth: true, description: 'Revoke a specific session' },
      { method: 'POST', path: '/authentication/change-password', auth: true, description: 'Change password (requires old password)' },
      { method: 'POST', path: '/authentication/verify-account', auth: true, description: 'Verify OTP for logged in account' },
      { method: 'GET', path: '/authentication/me/permissions', auth: true, description: 'Get roles, permissions, Casbin rules' },
      { method: 'GET', path: '/authentication/users', auth: true, description: 'List users linked to account' },
      { method: 'GET', path: '/authentication/user/{userid}', auth: true, description: 'User details by ID' },
      { method: 'POST', path: '/authentication/users/activate', auth: true, description: 'Activate account' },
      { method: 'POST', path: '/authentication/users/deactivate', auth: true, description: 'Deactivate account' },
    ],
    dataModels: ['Account', 'AccountLogin', 'Token', 'Session', 'AccountInfo', 'AccountProfileUpdate', 'TokenIntrospectResponse'],
  },
  {
    key: 'governance',
    name: 'Governance',
    type: 'Platform',
    mountPoints: ['/governance'],
    description: 'Core governance platform: multi-tenant RBAC, manage users/roles/permissions/policies, data catalog, data mesh, and infrastructure orchestration.',
    status: 'stable',
    icon: 'pi pi-shield',
    features: [
      { name: 'Multi-tenant RBAC', description: 'Casbin domain-based RBAC with (sub, dom, obj, act) model' },
      { name: 'Tenant Management', description: 'CRUD tenants, member invite/remove, tenant isolation' },
      { name: 'User & Account', description: 'User profiles linked with accounts, role assignment' },
      { name: 'Role & Permission', description: 'Hierarchical roles with permission bundles' },
      { name: 'Policy Engine', description: 'Fine-grained policies with conditions, priority, effect' },
      { name: 'Team Management', description: 'Teams with roles, member management' },
      { name: 'Data Catalog', description: 'Domain catalog — data domains, data products, assets' },
      { name: 'Asset Lineage', description: 'Tracking data asset lineage and relationships' },
      { name: 'Entitlements', description: 'Data access entitlements per user/team' },
      { name: 'Branch Management', description: 'Organizational branch hierarchy' },
      { name: 'Init Bootstrap', description: 'Seed default roles/policies for new tenant' },
      { name: 'Casbin Direct API', description: 'CRUD Casbin rules directly (admin only)' },
      { name: 'OpenAPI Export', description: 'Export domain OpenAPI specs' },
      { name: 'Infra Orchestration', description: 'Unified management of Docker, Kafka, K8s, GCP, ELK, Prometheus, Grafana' },
    ],
    endpoints: [
      { method: 'GET', path: '/governance/accounts', auth: true, description: 'List accounts' },
      { method: 'POST', path: '/governance/accounts', auth: true, description: 'Create account' },
      { method: 'GET', path: '/governance/accounts/{id}', auth: true, description: 'Account details' },
      { method: 'GET', path: '/governance/users', auth: true, description: 'List users by tenant' },
      { method: 'POST', path: '/governance/users', auth: true, description: 'Create user' },
      { method: 'GET', path: '/governance/roles', auth: true, description: 'List roles' },
      { method: 'POST', path: '/governance/roles', auth: true, description: 'Create role' },
      { method: 'GET', path: '/governance/permissions', auth: true, description: 'List permissions' },
      { method: 'POST', path: '/governance/permissions', auth: true, description: 'Create permission' },
      { method: 'GET', path: '/governance/policies', auth: true, description: 'List policies' },
      { method: 'POST', path: '/governance/policies', auth: true, description: 'Create policy' },
      { method: 'PATCH', path: '/governance/policies/{id}/enable', auth: true, description: 'Enable policy' },
      { method: 'GET', path: '/governance/teams', auth: true, description: 'List teams' },
      { method: 'POST', path: '/governance/teams', auth: true, description: 'Create team' },
      { method: 'GET', path: '/governance/tenants', auth: true, description: 'List tenants' },
      { method: 'POST', path: '/governance/tenants', auth: true, description: 'Create tenant' },
      { method: 'POST', path: '/governance/tenants/{id}/invite', auth: true, description: 'Invite member to tenant' },
      { method: 'GET', path: '/governance/casbin', auth: true, description: 'List Casbin rules' },
      { method: 'POST', path: '/governance/casbin', auth: true, description: 'Add Casbin rule' },
      { method: 'DELETE', path: '/governance/casbin', auth: true, description: 'Remove Casbin rule' },
      { method: 'POST', path: '/governance/init', auth: true, description: 'Bootstrap tenant — seed roles, policies' },
      { method: 'GET', path: '/governance/entitlements', auth: true, description: 'List entitlements' },
      { method: 'GET', path: '/governance/branches', auth: true, description: 'List branches' },
      { method: 'GET', path: '/governance/assets', auth: true, description: 'List data assets' },
      { method: 'GET', path: '/governance/data-products', auth: true, description: 'List data products' },
      { method: 'GET', path: '/governance/catalog', auth: true, description: 'Domain catalog listing' },
      { method: 'GET', path: '/governance/openapi-export', auth: true, description: 'Export domain OpenAPI specs' },
    ],
    dataModels: ['Tenant', 'Account', 'User', 'Role', 'Permission', 'Policy', 'Team', 'Domain', 'DataProduct', 'Asset', 'CasbinRule'],
  },
  {
    key: 'retail',
    name: 'Retail',
    type: 'Domain Adapter',
    mountPoints: ['/retail', '/data-mesh/domains/retail'],
    description: 'Integrated commerce platform — manage products, orders, inventory, loyalty members, marketing campaigns, and shipping logistics.',
    status: 'stable',
    icon: 'pi pi-shopping-bag',
    features: [
      { name: 'Products & Partners', description: 'CRUD products, partners, categories' },
      { name: 'Inventory & Logistics', description: 'Warehouses, stock levels, logistics coordination' },
      { name: 'Orders & Transactions', description: 'CRUD orders, tracking, transactions' },
      { name: 'Trip Management', description: 'Manage delivery trips, vehicles, routes' },
      { name: 'Admin', description: 'Health check, system status' },
    ],
    endpoints: [
      { method: 'GET', path: '/retail/products', auth: true, description: 'List products (pagination, filter)' },
      { method: 'POST', path: '/retail/products', auth: true, description: 'Create new product' },
      { method: 'GET', path: '/retail/products/{id}', auth: true, description: 'Product details' },
      { method: 'PUT', path: '/retail/products/{id}', auth: true, description: 'Update product' },
      { method: 'DELETE', path: '/retail/products/{id}', auth: true, description: 'Delete product' },
      { method: 'GET', path: '/retail/categories', auth: true, description: 'Product categories' },
      { method: 'GET', path: '/retail/partners', auth: true, description: 'Partners / suppliers' },
      { method: 'GET', path: '/retail/inventory', auth: true, description: 'Inventory by product/warehouse' },
      { method: 'POST', path: '/retail/inventory/adjust', auth: true, description: 'Adjust inventory' },
      { method: 'GET', path: '/retail/warehouses', auth: true, description: 'List warehouses' },
      { method: 'POST', path: '/retail/warehouses', auth: true, description: 'Create warehouse' },
      { method: 'GET', path: '/retail/orders', auth: true, description: 'List orders (filter by status, customer)' },
      { method: 'POST', path: '/retail/orders', auth: true, description: 'Create order' },
      { method: 'GET', path: '/retail/orders/{id}', auth: true, description: 'Order details' },
      { method: 'PATCH', path: '/retail/orders/{id}/status', auth: true, description: 'Update order status' },
      { method: 'GET', path: '/retail/transactions', auth: true, description: 'Transaction history' },
      { method: 'GET', path: '/retail/trips', auth: true, description: 'List delivery trips' },
      { method: 'POST', path: '/retail/trips', auth: true, description: 'Create delivery trip' },
      { method: 'PATCH', path: '/retail/trips/{id}/status', auth: true, description: 'Update trip status' },
      { method: 'GET', path: '/retail/vehicles', auth: true, description: 'List vehicles' },
      { method: 'POST', path: '/retail/vehicles', auth: true, description: 'Add vehicle' },
    ],
    dataModels: ['Product', 'Order', 'OrderItem', 'Inventory', 'Warehouse', 'Member', 'Campaign', 'Trip', 'Vehicle'],
  },
  {
    key: 'hotel',
    name: 'Hotel',
    type: 'Domain Adapter',
    mountPoints: ['/hotel', '/data-mesh/domains/hotel'],
    description: 'Hotel management system — property management, room booking, guest management, reviews & ratings.',
    status: 'stable',
    icon: 'pi pi-building',
    features: [
      { name: 'Apartment Management', description: 'CRUD apartments/properties (name, address, amenities, capacity)' },
      { name: 'Room Management', description: 'CRUD rooms in an apartment (type, price, available status)' },
      { name: 'Booking System', description: 'Booking, confirm, cancel, check-in, check-out' },
      { name: 'Guest Reviews', description: 'Text reviews after check-out' },
      { name: 'Ratings', description: 'Numerical rating (star rating) per booking' },
      { name: 'Health Check', description: 'Endpoint to check module status' },
    ],
    endpoints: [
      { method: 'GET', path: '/hotel/apartments', auth: true, description: 'List apartments' },
      { method: 'POST', path: '/hotel/apartments', auth: true, description: 'Create new apartment' },
      { method: 'GET', path: '/hotel/apartments/{id}', auth: true, description: 'Apartment details' },
      { method: 'PUT', path: '/hotel/apartments/{id}', auth: true, description: 'Update apartment' },
      { method: 'DELETE', path: '/hotel/apartments/{id}', auth: true, description: 'Delete apartment' },
      { method: 'GET', path: '/hotel/rooms', auth: true, description: 'List rooms (filter by apartment, status)' },
      { method: 'POST', path: '/hotel/rooms', auth: true, description: 'Create room' },
      { method: 'GET', path: '/hotel/rooms/{id}', auth: true, description: 'Room details' },
      { method: 'PUT', path: '/hotel/rooms/{id}', auth: true, description: 'Update room' },
      { method: 'GET', path: '/hotel/bookings', auth: true, description: 'List bookings (filter by guest, status)' },
      { method: 'POST', path: '/hotel/bookings', auth: true, description: 'Create booking' },
      { method: 'GET', path: '/hotel/bookings/{id}', auth: true, description: 'Booking details' },
      { method: 'PATCH', path: '/hotel/bookings/{id}/status', auth: true, description: 'Update status (confirm, check-in, check-out, cancel)' },
      { method: 'GET', path: '/hotel/reviews', auth: true, description: 'List reviews' },
      { method: 'POST', path: '/hotel/reviews', auth: true, description: 'Create review' },
      { method: 'GET', path: '/hotel/ratings', auth: true, description: 'List ratings' },
      { method: 'POST', path: '/hotel/ratings', auth: true, description: 'Submit rating' },
      { method: 'GET', path: '/hotel/health', auth: false, description: 'Health check' },
    ],
    dataModels: ['Apartment', 'Room', 'Booking', 'Review', 'Rating'],
  },
  {
    key: 'blogger',
    name: 'Blogger',
    type: 'Domain Adapter',
    mountPoints: ['/blogger', '/data-mesh/domains/blogger'],
    description: 'Blog content management system — posts, authors, categories, tags with lifecycle workflow.',
    status: 'stable',
    icon: 'pi pi-pencil',
    features: [
      { name: 'Post Management', description: 'CRUD posts with rich content, markdown support' },
      { name: 'Author Management', description: 'Manage authors with profile and bio' },
      { name: 'Category & Tags', description: 'Categorize content by category and tags' },
      { name: 'Post Lifecycle', description: 'Draft → Review → Published → Archived workflow' },
      { name: 'SEO Metadata', description: 'Slug, meta description, canonical URL' },
      { name: 'Content Versioning', description: 'Track edit history' },
    ],
    endpoints: [
      { method: 'GET', path: '/blogger/posts', auth: true, description: 'List posts (filter: status, author, category)' },
      { method: 'POST', path: '/blogger/posts', auth: true, description: 'Create new post (default status=DRAFT)' },
      { method: 'GET', path: '/blogger/posts/{id}', auth: true, description: 'Post details' },
      { method: 'PUT', path: '/blogger/posts/{id}', auth: true, description: 'Update post' },
      { method: 'DELETE', path: '/blogger/posts/{id}', auth: true, description: 'Delete post' },
      { method: 'PATCH', path: '/blogger/posts/{id}/publish', auth: true, description: 'Publish post' },
      { method: 'PATCH', path: '/blogger/posts/{id}/archive', auth: true, description: 'Archive post' },
      { method: 'GET', path: '/blogger/authors', auth: true, description: 'List authors' },
      { method: 'POST', path: '/blogger/authors', auth: true, description: 'Create author' },
      { method: 'GET', path: '/blogger/categories', auth: true, description: 'List categories' },
      { method: 'POST', path: '/blogger/categories', auth: true, description: 'Create category' },
    ],
    dataModels: ['Post', 'Author', 'Category'],
  },
  {
    key: 'cmc',
    name: 'CMC',
    type: 'Domain Adapter',
    mountPoints: ['/cmc', '/data-mesh/domains/cmc'],
    description: 'Omnichannel messaging platform — Telegram webhook, omnichannel messaging, template management, chatbot automation.',
    status: 'stable',
    icon: 'pi pi-comments',
    features: [
      { name: 'Telegram Webhook', description: 'Receive and process Telegram bot updates' },
      { name: 'Omnichannel Routing', description: 'Unify messages from multiple channels' },
      { name: 'Template Management', description: 'Manage message templates (notification, marketing)' },
      { name: 'Bot Automation', description: 'Rule-based chatbot responses' },
      { name: 'Channel Management', description: 'Configure channels (Telegram, Facebook, Email)' },
      { name: 'Task Queue', description: 'Background task processing via Celery' },
    ],
    endpoints: [
      { method: 'POST', path: '/cmc/telegram/webhook', auth: false, description: 'Telegram bot webhook receiver' },
      { method: 'GET', path: '/cmc/telegram/webhook', auth: false, description: 'Telegram webhook verification' },
      { method: 'GET', path: '/cmc/channels', auth: true, description: 'List messaging channels' },
      { method: 'POST', path: '/cmc/channels', auth: true, description: 'Create new channel' },
      { method: 'GET', path: '/cmc/channels/{id}', auth: true, description: 'Channel details' },
      { method: 'PUT', path: '/cmc/channels/{id}', auth: true, description: 'Update channel' },
      { method: 'GET', path: '/cmc/messages', auth: true, description: 'List messages (filter by channel, sender)' },
      { method: 'POST', path: '/cmc/messages/send', auth: true, description: 'Send message via channel' },
      { method: 'GET', path: '/cmc/templates', auth: true, description: 'List templates' },
      { method: 'POST', path: '/cmc/templates', auth: true, description: 'Create template' },
      { method: 'POST', path: '/cmc/templates/{id}/send', auth: true, description: 'Send message from template' },
      { method: 'GET', path: '/cmc/bots', auth: true, description: 'List bots' },
      { method: 'POST', path: '/cmc/bots', auth: true, description: 'Create bot' },
    ],
    dataModels: ['Channel', 'Message', 'Template', 'Bot', 'BotRule'],
  },
  {
    key: 'travel',
    name: 'Travel',
    type: 'Domain Adapter',
    mountPoints: ['/travel', '/data-mesh/domains/travel'],
    description: 'Travel management — trips, destinations, itineraries. Some endpoints are public (no auth required).',
    status: 'stable',
    icon: 'pi pi-globe',
    features: [
      { name: 'Destinations', description: 'Browse destinations with info, photos, highlights' },
      { name: 'Trips', description: 'Tour packages with itinerary, pricing, availability' },
      { name: 'Itinerary Builder', description: 'Customize day-by-day itinerary' },
      { name: 'Booking', description: 'Book tour with passenger info and payment' },
      { name: 'Public Browse', description: 'View destinations/trips without logging in' },
    ],
    endpoints: [
      { method: 'GET', path: '/data-mesh/domains/travel/destinations', auth: false, description: 'Browse destinations (public)' },
      { method: 'GET', path: '/data-mesh/domains/travel/destinations/{id}', auth: false, description: 'Destination detail (public)' },
      { method: 'GET', path: '/data-mesh/domains/travel/trips', auth: false, description: 'List available trips (public)' },
      { method: 'GET', path: '/data-mesh/domains/travel/trips/{id}', auth: false, description: 'Trip detail + itinerary (public)' },
      { method: 'POST', path: '/travel/destinations', auth: true, description: 'Create destination' },
      { method: 'PUT', path: '/travel/destinations/{id}', auth: true, description: 'Update destination' },
      { method: 'POST', path: '/travel/trips', auth: true, description: 'Create trip/tour package' },
      { method: 'PUT', path: '/travel/trips/{id}', auth: true, description: 'Update trip' },
      { method: 'PATCH', path: '/travel/trips/{id}/status', auth: true, description: 'Activate/deactivate trip' },
      { method: 'POST', path: '/travel/bookings', auth: true, description: 'Book tour' },
      { method: 'GET', path: '/travel/bookings', auth: true, description: "List user's bookings" },
      { method: 'GET', path: '/travel/bookings/{id}', auth: true, description: 'Booking details' },
      { method: 'PATCH', path: '/travel/bookings/{id}/cancel', auth: true, description: 'Cancel booking' },
    ],
    dataModels: ['Destination', 'Trip', 'Itinerary', 'ItineraryDay', 'Booking'],
  },
  {
    key: 'chat',
    name: 'Chat',
    type: 'Domain Adapter',
    mountPoints: ['/chat', '/data-mesh/domains/chat'],
    description: 'Messaging infrastructure for real-time communication. Minimal implementation — currently no HTTP routes exposed.',
    status: 'minimal',
    icon: 'pi pi-inbox',
    features: [
      { name: 'Direct messaging (1:1)', description: 'Planned' },
      { name: 'Group chat', description: 'Planned' },
      { name: 'Message history', description: 'Planned' },
      { name: 'WebSocket real-time', description: 'Planned' },
      { name: 'File sharing', description: 'Planned' },
      { name: 'Message search', description: 'Planned' },
    ],
    endpoints: [],
    dataModels: [],
  },
  {
    key: 'pipeline',
    name: 'Pipeline',
    type: 'Domain Adapter',
    mountPoints: ['/pipeline', '/data-mesh/domains/pipeline'],
    description: 'ETL orchestration and data pipeline management.',
    status: 'stable',
    icon: 'pi pi-sitemap',
    features: [
      { name: 'Pipeline CRUD', description: 'Create and manage pipeline definitions' },
      { name: 'Pipeline Runs', description: 'Trigger and track pipeline executions' },
      { name: 'Stage Management', description: 'Multi-stage pipelines with dependencies' },
      { name: 'Data Source/Sink', description: 'Configure data sources and sinks' },
      { name: 'Run Monitoring', description: 'Real-time status, logs, error tracking' },
    ],
    endpoints: [
      { method: 'GET', path: '/pipeline/pipelines', auth: true, description: 'List pipelines' },
      { method: 'POST', path: '/pipeline/pipelines', auth: true, description: 'Create pipeline' },
      { method: 'GET', path: '/pipeline/pipelines/{id}', auth: true, description: 'Pipeline details' },
      { method: 'PUT', path: '/pipeline/pipelines/{id}', auth: true, description: 'Update pipeline' },
      { method: 'DELETE', path: '/pipeline/pipelines/{id}', auth: true, description: 'Delete pipeline' },
      { method: 'POST', path: '/pipeline/pipelines/{id}/run', auth: true, description: 'Trigger pipeline run' },
      { method: 'GET', path: '/pipeline/runs', auth: true, description: 'List pipeline runs' },
      { method: 'GET', path: '/pipeline/runs/{id}', auth: true, description: 'Run details + logs' },
      { method: 'POST', path: '/pipeline/runs/{id}/cancel', auth: true, description: 'Cancel running pipeline' },
      { method: 'GET', path: '/pipeline/sources', auth: true, description: 'List data sources' },
      { method: 'POST', path: '/pipeline/sources', auth: true, description: 'Create data source' },
    ],
    dataModels: ['Pipeline', 'Stage', 'PipelineRun', 'DataSource', 'DataSink'],
  },
  {
    key: 'model',
    name: 'Model',
    type: 'Domain Adapter',
    mountPoints: ['/model', '/data-mesh/domains/model'],
    description: 'ML model registry — versioning, deployment tracking, and performance monitoring for machine learning models.',
    status: 'stable',
    icon: 'pi pi-cog',
    features: [
      { name: 'Model Registry', description: 'Register and catalog ML models' },
      { name: 'Version Management', description: 'Track multiple versions with metadata' },
      { name: 'Deployment Tracking', description: 'Record deployment environments (dev/staging/prod)' },
      { name: 'Metrics & Monitoring', description: 'Track accuracy, latency, drift metrics' },
      { name: 'Model Comparison', description: 'Compare metrics between versions' },
      { name: 'Lifecycle Management', description: 'Promote, deprecate, retire models' },
    ],
    endpoints: [
      { method: 'GET', path: '/model/models', auth: true, description: 'List ML models' },
      { method: 'POST', path: '/model/models', auth: true, description: 'Register new model' },
      { method: 'GET', path: '/model/models/{id}', auth: true, description: 'Model details' },
      { method: 'GET', path: '/model/models/{id}/versions', auth: true, description: 'List model versions' },
      { method: 'POST', path: '/model/models/{id}/versions', auth: true, description: 'Create new version' },
      { method: 'GET', path: '/model/versions/{id}', auth: true, description: 'Version details' },
      { method: 'PATCH', path: '/model/versions/{id}/promote', auth: true, description: 'Promote version to production' },
      { method: 'PATCH', path: '/model/versions/{id}/deprecate', auth: true, description: 'Deprecate version' },
      { method: 'GET', path: '/model/deployments', auth: true, description: 'List deployments' },
      { method: 'POST', path: '/model/deployments', auth: true, description: 'Deploy model version' },
      { method: 'GET', path: '/model/metrics/{version_id}', auth: true, description: 'Performance metrics' },
    ],
    dataModels: ['MLModel', 'ModelVersion', 'Deployment', 'ModelMetrics'],
  },
  {
    key: 'uploads',
    name: 'Uploads',
    type: 'Domain Adapter',
    mountPoints: ['/uploads', '/data-mesh/domains/uploads'],
    description: 'File upload service — supports both Google Cloud Storage (GCS) and AWS S3 backends.',
    status: 'stable',
    icon: 'pi pi-upload',
    features: [
      { name: 'Multi-backend', description: 'Support GCS and S3 (configured via env vars)' },
      { name: 'File Validation', description: 'Validate MIME type, file size' },
      { name: 'Presigned URLs', description: 'Generate time-limited access URLs' },
      { name: 'Public Upload', description: 'Upload and receive public URL immediately' },
      { name: 'Multipart Upload', description: 'Support large file multipart upload' },
      { name: 'Metadata', description: 'Save file metadata (name, size, type, uploader)' },
    ],
    endpoints: [
      { method: 'POST', path: '/uploads/', auth: true, description: 'Upload file, return URL' },
      { method: 'POST', path: '/uploads/presigned', auth: true, description: 'Generate presigned upload URL' },
      { method: 'GET', path: '/uploads/{file_id}', auth: true, description: 'File metadata' },
      { method: 'DELETE', path: '/uploads/{file_id}', auth: true, description: 'Delete file' },
      { method: 'GET', path: '/uploads/', auth: true, description: 'List files of user' },
    ],
    dataModels: ['FileMetadata'],
  },
  {
    key: 'databricks',
    name: 'Databricks',
    type: 'Domain Adapter',
    mountPoints: ['/databricks', '/data-mesh/domains/databricks'],
    description: 'Databricks integration — manage jobs, clusters, notebooks via Databricks REST API.',
    status: 'stable',
    icon: 'pi pi-database',
    features: [
      { name: 'Job Management', description: 'List, trigger, monitor Databricks jobs' },
      { name: 'Cluster Management', description: 'Start, stop, resize clusters' },
      { name: 'Notebook Operations', description: 'List, run notebooks' },
      { name: 'Run Monitoring', description: 'Track job run status, logs, output' },
    ],
    endpoints: [
      { method: 'GET', path: '/databricks/jobs', auth: true, description: 'List Databricks jobs' },
      { method: 'POST', path: '/databricks/jobs/{id}/run', auth: true, description: 'Trigger job run' },
      { method: 'GET', path: '/databricks/runs/{id}', auth: true, description: 'Job run status + output' },
      { method: 'GET', path: '/databricks/clusters', auth: true, description: 'List clusters' },
      { method: 'POST', path: '/databricks/clusters/{id}/start', auth: true, description: 'Start cluster' },
      { method: 'POST', path: '/databricks/clusters/{id}/stop', auth: true, description: 'Stop cluster' },
      { method: 'GET', path: '/databricks/notebooks', auth: true, description: 'List notebooks' },
      { method: 'POST', path: '/databricks/notebooks/run', auth: true, description: 'Run notebook' },
    ],
    dataModels: [],
  },
  {
    key: 'dockerhub',
    name: 'DockerHub',
    type: 'Domain Adapter',
    mountPoints: ['/dockerhub', '/data-mesh/domains/dockerhub'],
    description: 'Docker Registry integration — manage container images, repositories and tags.',
    status: 'stable',
    icon: 'pi pi-cloud',
    features: [
      { name: 'Repository Listing', description: 'List Docker repositories in an organization/user' },
      { name: 'Tag Management', description: 'List, inspect, delete image tags' },
      { name: 'Image Metadata', description: 'View image size, layers, digest' },
      { name: 'Pull Statistics', description: 'Track pull counts per repository' },
    ],
    endpoints: [
      { method: 'GET', path: '/dockerhub/repositories', auth: true, description: 'List repositories' },
      { method: 'GET', path: '/dockerhub/repositories/{name}', auth: true, description: 'Repository detail' },
      { method: 'GET', path: '/dockerhub/repositories/{name}/tags', auth: true, description: 'List image tags' },
      { method: 'GET', path: '/dockerhub/repositories/{name}/tags/{tag}', auth: true, description: 'Tag/image detail' },
      { method: 'DELETE', path: '/dockerhub/repositories/{name}/tags/{tag}', auth: true, description: 'Delete tag' },
      { method: 'GET', path: '/dockerhub/repositories/{name}/manifests/{ref}', auth: true, description: 'Image manifest' },
    ],
    dataModels: [],
  },
  {
    key: 'facebook',
    name: 'Facebook',
    type: 'Domain Adapter',
    mountPoints: ['/facebook', '/data-mesh/domains/facebook'],
    description: 'Facebook integration — Graph API, Messenger webhook, and OAuth flow.',
    status: 'stable',
    icon: 'pi pi-facebook',
    features: [
      { name: 'Webhook Receiver', description: 'Receive Messenger updates from Facebook' },
      { name: 'Webhook Verification', description: 'Handle hub challenge verification' },
      { name: 'Send Messages', description: 'Send messages via Messenger API' },
      { name: 'OAuth Flow', description: 'Facebook OAuth authentication' },
      { name: 'Page Management', description: 'Manage Facebook Pages' },
    ],
    endpoints: [
      { method: 'GET', path: '/facebook/webhook', auth: false, description: 'Webhook verification (hub.challenge)' },
      { method: 'POST', path: '/facebook/webhook', auth: false, description: 'Receive Messenger updates' },
      { method: 'GET', path: '/facebook/oauth', auth: true, description: 'Initiate Facebook OAuth' },
      { method: 'GET', path: '/facebook/oauth/callback', auth: false, description: 'OAuth callback' },
      { method: 'POST', path: '/facebook/messages/send', auth: true, description: 'Send message via Messenger' },
      { method: 'GET', path: '/facebook/pages', auth: true, description: 'List Pages' },
    ],
    dataModels: [],
  },
  {
    key: 'google',
    name: 'Google',
    type: 'Domain Adapter',
    mountPoints: ['/google', '/data-mesh/domains/google'],
    description: 'Google services integration — OAuth2 callback handler and Google APIs (Drive, Sheets, Calendar...).',
    status: 'stable',
    icon: 'pi pi-google',
    features: [
      { name: 'OAuth2 Callback', description: 'Receive and process authorization code from Google' },
      { name: 'Token Exchange', description: 'Exchange code → access_token + refresh_token' },
      { name: 'Google Drive', description: 'Browse, upload, download files' },
      { name: 'Google Sheets', description: 'Read/write spreadsheet data' },
      { name: 'Token Refresh', description: 'Automatically refresh Google access token' },
    ],
    endpoints: [
      { method: 'GET', path: '/google/callback', auth: false, description: 'OAuth2 callback — receive ?code= from Google' },
      { method: 'GET', path: '/google/drive/files', auth: true, description: 'List Google Drive files' },
      { method: 'POST', path: '/google/drive/upload', auth: true, description: 'Upload file to Drive' },
      { method: 'GET', path: '/google/sheets/{spreadsheet_id}', auth: true, description: 'Read spreadsheet' },
      { method: 'PUT', path: '/google/sheets/{spreadsheet_id}/range/{range}', auth: true, description: 'Write to spreadsheet range' },
      { method: 'GET', path: '/google/profile', auth: true, description: "User's Google profile" },
    ],
    dataModels: [],
  },
];
